name: build

on: [ push ]

jobs:
  linux:
    name: 'Linux'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: burrunan/gradle-cache-action@v1
        name: Build BigVolumeViewer
        with:
          arguments: build

  windows:
    name: 'Windows'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: burrunan/gradle-cache-action@v1
        name: Build BigVolumeViewer
        with:
          arguments: build

  mac:
    name: 'Mac OS'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: burrunan/gradle-cache-action@v1
        name: Build BigVolumeViewer
        with:
          arguments: build
